Duplicate item
gridsuite/gridexplore-app pull request #100
Opened 2022-05-17 09:24 UTC by Meklo

2022-05-19 07:44 UTC, FranckLecuyer requested changes

2022-05-19 07:44 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +    console.info('Creating a new case...');
Typo : Duplicating a case

2022-05-19 07:44 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +    urlSearchParams.append('parentStudyUuid', parentStudyUuid);
parameter not used in explore server

2022-05-19 07:44 UTC, FranckLecuyer commented on src/components/menus/content-contextual-menu.js
> +            elementExists(
Maybe later, add an api in directory server to generate a new unique name, and use it here ...

2022-05-19 07:44 UTC, FranckLecuyer commented on src/components/menus/content-contextual-menu.js
> +                activeElement.elementName + duplicateSuffix,
Maybe use a local variable, set to : activeElement.elementName + duplicateSuffix
and use it elsewhere

2022-05-19 07:44 UTC, FranckLecuyer commented on src/components/menus/content-contextual-menu.js
> +                                    setHideMenu(false);
Maybe handleCloseDialog() ?

2022-05-30 08:03 UTC, AbdelHedhili approved these changes

2022-05-30 11:56 UTC, FranckLecuyer approved these changes

2022-06-10 09:18 UTC, merged