Refresh directories and elements
gridsuite/gridexplore-app pull request #145
Opened 2022-09-21 13:05 UTC by bendaamerahm

2022-10-12 14:30 UTC, sBouzols requested changes
Some code review comments, will test

2022-10-12 14:30 UTC, sBouzols commented on package-lock.json
>          },
The package-lock.json shouldn't change in this PR I think.

2022-10-12 14:30 UTC, sBouzols commented on src/components/tree-views-container.js
> +    }, [dispatch]);
there is no calls to dispatch in here... remove this dependency ? Then the effect will be run only on componentDidMount ?

2022-10-12 14:30 UTC, sBouzols commented on src/utils/rest-api.js
> +export function connectNotificationsWsUpdateDirectory() {
a bit lower :
'Connected Websocket update ~~studies~~ directories '

2022-10-12 14:30 UTC, sBouzols commented on src/redux/reducer.js
> +            force: 1 - state.directoryUpdated.force,
Why this substraction ?

2022-10-12 14:30 UTC, sBouzols commented on src/components/tree-views-container.js
>              console.debug('Received Update Studies notification', event);
`directories` then ?

2022-10-12 14:30 UTC, sBouzols commented on src/components/tree-views-container.js
> +            dispatch(directoryUpdated(eventData));
Maybe this is the only thing to do when initializing the websocket : 
```
wsRef.current.onmessage = (event) => { 
  let eventData = JSON.parse(event.data);
  if (!eventData.headers) {
      return;
  }
  dispatch(directoryUpdated(eventData));
};
```
Then the current onUpdateStudies function becomes an effect which proc when directoryUpdated changes in the store and consume differents types of notifications, you know like it's done in GridStudyApp

2022-10-12 14:30 UTC, sBouzols commented on src/components/dialogs/directory-selector.js
> +        (nodeId) => {
Maybe rename nodeId to directoryUuid it's a bit confusing

2022-10-12 14:30 UTC, sBouzols commented on src/components/dialogs/directory-selector.js
> +                    console.warn(
Maybe a snackbar output with a translated message instead of console warning ?

2022-10-20 14:27 UTC, bendaamerahm commented on src/redux/reducer.js
> +            force: 1 - state.directoryUpdated.force,
I did the same as gridStudy App

2022-10-25 15:22 UTC, sBouzols approved these changes
Code Review OK
Tests OK
Console Warning OK

2022-10-26 10:05 UTC, YenguiSeddik approved these changes
Test: ok
code review: ok

2022-10-26 10:05 UTC, merged