adjust coloumns width
gridsuite/gridexplore-app pull request #195
Opened 2023-01-11 13:02 UTC by Walid-Sahnoun

Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>

2023-01-16 08:09 UTC, EstherDarkish approved these changes

2023-01-16 08:28 UTC, EstherDarkish requested changes
Needs to see something with the product owners before validation.

2023-01-30 16:12 UTC, etiennehomer commented on src/components/directory-content.js
> +                            maxWidth: 140,
You can put 130 here. So last 4 columns have the same width

2023-01-30 16:33 UTC, Walid-Sahnoun commented on src/components/directory-content.js
> +                            maxWidth: 140,
i will use 135 for the last 4 columns for FR and EN

2023-01-30 16:42 UTC, etiennehomer approved these changes

2023-01-30 16:47 UTC, ayolab approved these changes

2023-01-31 08:55 UTC, EstherDarkish approved these changes

2023-01-31 08:56 UTC, merged