fix dialog default enter behaviour + sort elements in alphabetical order in directory-tree & directory-content
gridsuite/gridexplore-app pull request #22
Opened 2021-08-10 13:08 UTC by ChamseddineBhd

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

2021-08-10 15:06 UTC, sBouzols requested changes

2021-08-10 15:06 UTC, sBouzols commented on src/components/dialogs/delete-dialog.js
> +            handleClose();
Not sure here... I continue to think it should be handleClick even if its a delete dialog

2021-08-10 15:06 UTC, sBouzols commented on src/components/tree-views-container.js
> +                    children
Not sure if it's the right place to sort... I think it's better to do it during rendering like in renderTree for TreeItems...
Maybe move this sorting code somewhere in directory-content render method ?

2021-08-10 15:06 UTC, sBouzols commented on src/components/directory-tree-view.js
> +                    ? node.children
The sorting will not work for rootDirectories then (the first TreeItem in this recursive function)... we must add this sorting code in directory-container when we loop over rootdirectories to render TreeViews.

2021-08-10 15:06 UTC, sBouzols commented on src/components/directory-tree-view.js
> -        event.stopPropagation();
I don't see any differences then I imagine it's a good pratice to remove code which we don't understand behavior but maybe you could explain here why `event.stopPropagation()` and `e.preventDefault()` are useless

2021-08-10 15:24 UTC, ChamseddineBhd commented on src/components/directory-tree-view.js
> +                    ? node.children
it's already added

2021-08-10 15:34 UTC, ChamseddineBhd commented on src/components/directory-tree-view.js
> -        event.stopPropagation();
because we have added  event.preventDefault() in app.js in a previous commit

2021-08-11 07:44 UTC, sBouzols approved these changes

2021-08-11 08:43 UTC, merged