Add filter and contingency name
gridsuite/gridexplore-app pull request #230
Opened 2023-04-24 19:34 UTC by AAJELLAL

2023-04-25 07:00 UTC, laurgarn commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +    //TODO:CHECK THIS
Comment to be removed, especially as it appears no more relevent.

2023-04-25 07:01 UTC, laurgarn commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +        /** the name is accessible outside of the equipmentFilterForm */
Javadoc comment to be transformed to a one line comment `//``

2023-04-25 07:02 UTC, laurgarn commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +        /** check if ContingencyList  or filter is on creation mode */
javadoc comment to be transformed

2023-04-25 07:02 UTC, laurgarn commented on src/components/dialogs/criteria-based-filter-dialog.js
> +            /** name should be sent outside the equipmentFilterForm */
javadoc comment to be transformed

2023-04-25 07:03 UTC, laurgarn commented on src/components/dialogs/criteria-based-filter-dialog.js
> +                Object.assign({
Or just `{...filter, ... { name: filter.equipmentFilterForm.name} }`

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/explicit-naming-contingency-list-content.js
> +                        handleNameChange(response?.name ?? '');
Why call setValue through handleNameChange instead of directly ?

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/explicit-naming-filter-dialog-content.js
> +                        handleNameChange(response?.name ?? '');
Why not directly call setNameValue ?

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/filters.js
> +            if (name.replace(/ /g, '') !== '') {
`!name.match(/^\s*$/)` avoid the need for modification and second test

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/filters.js
> +        if (name !== '') {
I favor treating short things first. Here it would give : 
```
if (name === '') {
  // do the simple thing first
  setFormState('', false);
  setLoadingCheckName(false);
} else if (name.match(/^\s*$/) {
  setFormState(intl.formatMessage({ id: 'nameEmpty' }), false);
  setLoadingCheckName(false);
} else {
  // do the big thing, keeping in sight the conditions above too
}
```

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/filters.js
> +    const setFormState = (errorMessage, isNameValid) => {
Why passing errorMessage then ?

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/filters.js
> +    /** don't show the name field if not edit mode */
javadoc style comment should be used only for javadoc

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/name-filter-or-contingency.js
> +            'linear-gradient(rgba(255, 255, 255, 0.16), rgba(255, 255, 255, 0.16))',
I guess this is copied from filter.js, but I don't understand this gradient where the two ends are the same color with the same alpha.

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/name-filter-or-contingency.js
> +        if (name !== '') {
Same remark**s** as in filters.js

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/name-filter-or-contingency.js
> +        const showOk = newName !== '' && !loadingCheckName && nameValid;
Thank you for the local const :-)

2023-04-25 07:34 UTC, laurgarn commented on src/components/dialogs/name-filter-or-contingency.js
> +    /** don't show the name field if not edit mode */
javadoc style comment. Please don't

2023-04-25 07:34 UTC, laurgarn commented on src/components/directory-content.js
> +            /** set active directory on the store because it will be used while editing the contingency name */
javadoc style comment to simplify

2023-04-25 07:34 UTC, laurgarn commented on src/utils/rest-api.js
>      let url = PREFIX_ACTIONS_QUERIES;
When does this initialisation is still used ?
Chances are (I've not read the specifications) that one could factorize out
that `PREFIX_EXPLORE_SERVER_QUERIES + /v1/explore/` here and use it in each _rung_ of the if _ladder_

2023-05-11 13:34 UTC, klesaulnier commented on src/translations/fr.json
> +    "Name": "Name",
use existing nameProperty message

2023-05-11 13:34 UTC, archendel commented on src/components/dialogs/name-wrapper.js
> +    const [newName, setNewName] = useState('');
I think we only need one state to handle this

2023-05-11 13:34 UTC, klesaulnier commented on src/components/dialogs/name-wrapper.js
> +    const [errorMessage, setErrorMessage] = React.useState('');
we don't need nameValid boolean, this state is enough to check if there is an error or not

2023-05-11 13:34 UTC, archendel commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +    isModeCreation,
prop to remove

2023-05-11 13:34 UTC, klesaulnier commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +    isCreation,
we don't need both of those props

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/explicit-naming-contingency-list-content.js
> +                        handleNameChange(response?.name ?? '');
I prefer creating one function that handles the name change instead of calling setNameValue each time.This way if i have to add more controls in the future , it's easy to do it on one place.

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/criteria-based-filter-dialog.js
> +                Object.assign({
Indeed

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/filters.js
> +    const setFormState = (errorMessage, isNameValid) => {
My bad, I need to add an error message.

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/filters.js
> +        if (name !== '') {
I get it from another component, but I agree :) .

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +    //TODO:CHECK THIS
Done

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +        /** the name is accessible outside of the equipmentFilterForm */
Done

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/filters.js
> +            if (name.replace(/ /g, '') !== '') {
Done

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +    isCreation,
Done.

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/criteria-based-filter-dialog-content.js
> +    isModeCreation,
Done

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/name-wrapper.js
> +    const [errorMessage, setErrorMessage] = React.useState('');
Done

2023-05-25 07:47 UTC, AAJELLAL commented on src/components/dialogs/name-wrapper.js
> +    const [newName, setNewName] = useState('');
Done

2023-05-25 07:47 UTC, AAJELLAL commented on src/translations/fr.json
> +    "Name": "Name",
Done

2023-05-25 09:19 UTC, archendel requested changes

2023-05-25 09:19 UTC, klesaulnier commented on src/utils/equipment-types.js
> +
unnecessary file change

2023-05-25 09:19 UTC, klesaulnier commented on src/redux/reducer.js
> +    selectedElement: null,
why implementing selectedElement in store if we don't use any "useSelector" on this element ?
I don't think I've seen it used anywhere

2023-05-25 09:19 UTC, klesaulnier commented on src/components/dialogs/script-dialog-content.js
> +    handleNoEdition,
rename all handleNotEdit to onFetchedDataCallback

2023-05-25 17:08 UTC, AAJELLAL commented on src/components/dialogs/script-dialog-content.js
> +    handleNoEdition,
Done

2023-05-25 17:09 UTC, AAJELLAL commented on src/redux/reducer.js
> +    selectedElement: null,
Done. I used it at the beginning to get the initial name, but no need to it now.

2023-05-25 17:09 UTC, AAJELLAL commented on src/utils/equipment-types.js
> +
Done

2023-05-26 09:02 UTC, archendel approved these changes
typos and unnecessary changes
Test: OK
Code: OK

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/criteria-based-filter-dialog.js
> +    const [isNameValide, setIsNameValide] = useState(true);
typo : isNameValide -> isNameValid

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/explicit-naming-contingency-list-content.js
> +
unnecessary file change

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/explicit-naming-contingency-list-edit-dialog.js
> +    const [isNameValide, setIsNameValide] = useState(true);
typo : isNameValide -> isNameValid

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/explicit-naming-contingency-list-edit-dialog.js
> +        const areTableValuesValide =
typo : areTableValuesValid

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/explicit-naming-filter-creation-dialog.js
> +    const [isNameValide, setIsNameValide] = useState(true);
typo: isNameValid

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/explicit-naming-filter-dialog-content.js
>      useEffect(() => {
unnecessary file change

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/explicit-naming-filter-dialog-content.js
>      return (
unnecessary file change

2023-05-26 09:02 UTC, klesaulnier commented on src/components/dialogs/filters.js
>  export const filteredTypes = {
unnecessary file change

2023-05-26 09:02 UTC, archendel commented on src/utils/rest-api.js
>      return backendFetchJson(url);
unnecessary change

2023-05-30 12:41 UTC, sBouzols commented on src/components/dialogs/script-dialog.js
> +    const [isNameValide, setIsNameValide] = useState(true);
isNameValid~~e~~

2023-05-30 12:42 UTC, sBouzols commented on src/components/dialogs/name-wrapper.js
> + * Copyright (c) 2021, RTE (http://www.rte-france.com)
2023

2023-06-12 06:27 UTC, jonenst approved these changes

2023-06-12 07:16 UTC, merged