rework setTimeout with mui debounce
gridsuite/gridexplore-app pull request #234
Opened 2023-05-11 07:03 UTC by ghazwarhili

2023-05-25 13:50 UTC, sBouzols requested changes

2023-05-25 13:50 UTC, sBouzols commented on src/components/dialogs/create-contingency-list-dialog.js
> +    const debouncedUpdateContingencyFormState = useMemo(
useCallback

2023-05-25 13:50 UTC, sBouzols commented on src/components/dialogs/create-filter-dialog.js
> +    const debouncedUpdateFilterFormState = useMemo(
useCallback

2023-05-25 13:50 UTC, sBouzols commented on src/components/dialogs/field-hook.js
> +    const debouncedUpdateValidity = useMemo(
useCallback

2023-06-02 09:55 UTC, sBouzols commented on src/components/dialogs/create-contingency-list-dialog.js
> +    const debouncedUpdateContingencyFormState = useMemo(
nope useMemo is better you are right

2023-06-02 09:55 UTC, sBouzols commented on src/components/dialogs/create-filter-dialog.js
> +    const debouncedUpdateFilterFormState = useMemo(
nope useMemo is better you are right

2023-06-02 09:55 UTC, sBouzols commented on src/components/dialogs/field-hook.js
> +    const debouncedUpdateValidity = useMemo(
nope useMemo is better you are right

2023-06-02 09:56 UTC, sBouzols commented
Move your custom hook in commons-ui then use it here and all will be good :)
Same naming convention could be nice : `debounced...`

2023-06-05 08:18 UTC, jonenst approved these changes

2023-06-12 14:18 UTC, sBouzols approved these changes

2023-06-12 14:41 UTC, merged