Replace commonsui::useImportExportParams with commonsui::FlatParameters
gridsuite/gridexplore-app pull request #236
Opened 2023-05-25 12:57 UTC by trikimahdi

2023-05-26 11:49 UTC, Walid-Sahnoun requested changes
when create a new study, the selected extensions is not sent to the server

2023-05-26 12:47 UTC, sBouzols requested changes
will not consider parameters with those changes

2023-05-26 12:47 UTC, sBouzols commented on src/components/dialogs/create-study-dialog.js
> +    const [currentValues, setCurrentValues] = useState({});
same as the other PR : `[currentParameters, setCurrentParameters]`

2023-05-26 12:47 UTC, sBouzols commented on src/components/dialogs/create-study-dialog.js
> +    const defaultValues = useMemo(() => {
You don't need to do this, it's done in FlatParameters component

2023-05-26 12:47 UTC, sBouzols commented on src/components/dialogs/create-study-dialog.js
> +    const resetImportParamsToDefault = useCallback(() => {
You don't need to do this, it's done in FlatParameters component,
instead you should simply reset `setCurrentParameters({})` in `handleCloseDialog`

2023-05-30 11:57 UTC, sBouzols commented on src/components/dialogs/create-study-dialog.js
> +    extractDefaultMap,
Removed in the commons-ui PR : https://github.com/gridsuite/commons-ui/pull/266

2023-05-30 11:57 UTC, sBouzols commented on src/components/dialogs/create-study-dialog.js
> +    const paramsComponent = useMemo(() => {
I don't think we have to memoize this component `FlatParameters`, I don't think CreateStudyDialog render this much. It's overoptimized for me here, it could be directly in the JSX.

2023-06-08 13:23 UTC, sBouzols approved these changes
Code Review OK
Tests OK, 
* mode dark and light, 
* comparison with previous style.
* study creation still working fine
Console Warning check OK

2023-06-08 13:50 UTC, Walid-Sahnoun approved these changes
Code Review OK
Tests OK

2023-06-09 12:08 UTC, merged