use CustomMuiDialog and get initial name from directory-server
gridsuite/gridexplore-app pull request #285
Opened 2023-09-19 14:02 UTC by achour94

use CustomMuiDialog and UniqueNameInput instead of old implementation.
generate intial name from the directory server

2023-09-20 09:00 UTC, flomillot commented on src/components/dialogs/copy-to-script-dialog.tsx
> +const CopyToScriptDialog: React.FC<CopyToScriptDialogProps> = ({
I think we decided to use `FunctionalComponent` everywhere and not `FC`.

2023-09-20 09:00 UTC, flomillot commented on src/components/dialogs/copy-to-script-dialog.tsx
> +        reset(emptyFormData);
I don't think it's necessary

2023-09-20 09:00 UTC, flomillot commented on src/components/dialogs/copy-to-script-dialog.tsx
> +    onClick,
```suggestion
    onValidate,
```

2023-09-20 09:00 UTC, flomillot commented on src/components/dialogs/copy-to-script-dialog.tsx
> +    const onSubmit = (data: { [NAME]: string; [key: string]: any }) => {
Why `[key: string]: any` ?
If you want you can do like it's done for CreateCaseDialog with `IFormData` (you can remove the `I` before)

2023-09-20 09:00 UTC, flomillot commented on src/translations/en.json
> +  "generateCopyScriptNameError" : "An error occured while generating the copy script name of the element {itemName} : {errorMessage}",
I would not set the server error message into the snack bar displayed to the user. I don't know why it's done elsewhere but for me it's not a good practice. I asked on slack if we should do this or not.

2023-09-21 08:31 UTC, flomillot requested changes

2023-09-21 08:31 UTC, flomillot commented on src/components/dialogs/copy-to-script-dialog.tsx
> +interface IFormData {
Please remove the `I`

2023-09-21 10:40 UTC, flomillot approved these changes

2023-09-22 11:43 UTC, ghazwarhili approved these changes

2023-09-25 09:36 UTC, merged