US 593 Delete button with possible multi-selection
gridsuite/gridexplore-app pull request #30
Opened 2021-08-17 13:52 UTC by laurgarn

Adds a delete button that can handle multiple selection via checkboxes
https://dev.azure.com/GridSuite/MVP/_workitems/edit/593

2021-08-18 10:05 UTC, sBouzols requested changes
- Do not show toolbar if nothing selected
- Do not show button in toolbar if nothing selected
- vertical separator glitch(CSS)
- vertical scrollbar apparition in directory content at right of screen

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> +        return children.length === 1 && children[0].elementUuid === userId;
Compare `elementUuid with `userId` is dangerous

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> -        setAnchorEl(null);
do not remove this, to keep close contextual menu when opening dialogs

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> +                    msgs.push(intl.formatMessage({ id: 'deleteStudyError' }));
Maybe manage multiple errors when deleting multiple elements

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> +        if (selectedUuids.size !== 0) {
changes with not effect

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> +        BIG: 'GoogleMicrosoft', // if !selectedUuids.has(selected.Uuid) deselects selectedUuids
maybe we should extract this part in a contextualMenuSelectionPolicies.js file

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> +                isPrivate={() => true}
here we need a function which returns :
true if all selected studies are private
false if all are public
undefined otherwise

2021-08-18 10:05 UTC, sBouzols commented on src/components/directory-content.js
> +                        <DeleteIcon />
className={classes.icon}
18px / 18px

2021-08-23 08:16 UTC, laurgarn commented on src/components/directory-content.js
> +        BIG: 'GoogleMicrosoft', // if !selectedUuids.has(selected.Uuid) deselects selectedUuids
Why not, but afterward.

2021-08-23 13:38 UTC, sBouzols approved these changes

2021-08-23 13:43 UTC, merged