[WIP] add multi export for cases
gridsuite/gridexplore-app pull request #308
Opened 2023-11-29 14:27 UTC by ne0ds

2023-12-01 07:55 UTC, archendel approved these changes

2023-12-01 07:55 UTC, klesaulnier commented on package.json
revert changes since this file does not change

2023-12-04 07:39 UTC, ghazwarhili requested changes
Revert changes in the package json file

2023-12-04 09:03 UTC, ne0ds commented
> Revert changes in the package json file

Done !

2023-12-06 12:48 UTC, klesaulnier approved these changes

2023-12-06 16:21 UTC, ghazwarhili approved these changes

2023-12-11 13:21 UTC, merged