Fix description field
gridsuite/gridexplore-app pull request #325
Opened 2024-01-12 15:51 UTC by YenguiSeddik

2024-01-16 09:45 UTC, AAJELLAL requested changes
- The application crashes when creating a study or situation regardless of adding the description or not.
- The description counter needs some margin at the bottom.

2024-01-19 10:27 UTC, AAJELLAL approved these changes
Tests & code OK.

2024-01-22 08:40 UTC, AbdelHedhili approved these changes

2024-01-22 08:40 UTC, AbdelHedhili commented on src/translations/en.json
> -  "descriptionModificationDialog": "Description modification"
this wasn't used ?

2024-01-22 09:35 UTC, YenguiSeddik commented on src/translations/en.json
> -  "descriptionModificationDialog": "Description modification"
No, it was used in the description modification dialog but was replaced by "description": "Description",

2024-01-22 10:20 UTC, souissimai approved these changes
test ok

2024-01-22 12:21 UTC, merged