Add MCS Expert Filter front
gridsuite/gridexplore-app pull request #333
Opened 2024-01-23 16:44 UTC by lilian-houdelet

2024-01-31 18:08 UTC, dbraquart requested changes
code: ok
tests: Front works fine, but some translations are not conform

2024-01-31 18:08 UTC, dbraquart commented on src/translations/en.json
> +  "maxQAtNominalV": "Qmax available at nominal voltage",
```suggestion
  "maxQAtNominalV": "Available Qmax at nominal voltage",
```

2024-01-31 18:08 UTC, dbraquart commented on src/translations/en.json
> +  "maxSusceptance": "Maximal susceptance available",
```suggestion
  "maxSusceptance": "Maximum available susceptance",
```

2024-02-01 13:58 UTC, dbraquart approved these changes
code: ok
tests: not done with last commit

2024-02-01 15:36 UTC, flomillot commented on src/components/dialogs/filter/expert/expert-filter-constants.ts
> +    SWITCHED_ON_MAX_SUSCEPTANCE: {
Same as in backend, why with MAX ?

2024-02-01 16:55 UTC, flomillot approved these changes

2024-02-02 10:21 UTC, merged