Add Custom filter for lines
gridsuite/gridexplore-app pull request #339
Opened 2024-01-29 12:42 UTC by lilian-houdelet

2024-02-01 16:01 UTC, flomillot requested changes
Countries does not work
https://github.com/gridsuite/gridexplore-app/blob/b38ba7e5225bdfb6151ff512e2505b2d5b903d5a/src/components/utils/rqb-inputs/value-editor.tsx#L24

2024-02-01 16:52 UTC, flomillot commented on src/components/utils/rqb-inputs/value-editor.tsx
> +    if (
if (
        [FieldType.COUNTRY, FieldType.COUNTRY_1, FieldType.COUNTRY_2].includes(
            props.field as FieldType
        )
    )

Better than call toString() everytime, no ?

2024-02-07 14:30 UTC, flomillot requested changes

2024-02-07 14:30 UTC, flomillot commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
> +    if (microUnits.includes(field as FieldType)) {
```suggestion
    if (microUnits.includes(field)) {
```

2024-02-07 14:30 UTC, flomillot commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
> +
Why this code ?

2024-02-07 14:30 UTC, flomillot commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
> +                    ? updatedValue
```suggestion
                    ? changeValueUnit(rule.value, rule.field as FieldType)
```
Why not just this ?

2024-02-07 14:30 UTC, flomillot commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
>              values: isValueAnArray ? rule.value : undefined,
What about `values` ?

2024-02-07 14:30 UTC, flomillot commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
> +                    .map((value) => {
You can keep the previous code and add a new map right after, then we avoid duplicate code.

2024-02-07 14:34 UTC, lilian-houdelet commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
> +
we don't have any values for the operator EXISTS

2024-02-07 14:39 UTC, lilian-houdelet commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
> +
Not mandatory with the changes

2024-02-07 14:40 UTC, lilian-houdelet commented on src/components/dialogs/filter/expert/expert-filter-utils.ts
>              values: isValueAnArray ? rule.value : undefined,
I forgot, I'll update it

2024-02-07 16:24 UTC, flomillot approved these changes

2024-02-08 09:05 UTC, merged