Export case with choosen format
gridsuite/gridexplore-app pull request #353
Opened 2024-02-12 14:37 UTC by ne0ds

2024-02-15 15:33 UTC, EstherDarkish commented on src/translations/en.json
> +  "exportFormat": "Format of the export",
```suggestion
  "exportFormat": "Export format",
```

2024-02-15 16:39 UTC, EstherDarkish requested changes
When the backend returns a HTTP500 error code, the frontend do not treat the error. There is no snackbar, only a neverending loading icon.

2024-02-29 13:38 UTC, EstherDarkish commented on src/components/dialogs/export-case-dialog.tsx
> +                    </div>
We should use &lt;Box&gt; instead of &lt;div&gt;, and sx props instead of style

2024-02-29 13:38 UTC, EstherDarkish commented on src/translations/en.json
> +  "download.error": "An error occurred while exporting case {caseUuid}",
```suggestion
  "export.error": "An error occurred while exporting case {caseUuid}",
```

2024-02-29 13:38 UTC, EstherDarkish commented on src/translations/en.json
> +  "export": "Export"
```suggestion
  "export.message.formatMissing": "No export format specified",
  "export.format": "Export format",
  "export.button": "Export"
```

2024-02-29 18:08 UTC, EstherDarkish approved these changes

2024-03-08 16:11 UTC, SlimaneAmar commented on src/components/utils/caseUtils.ts
> +    const errors: ExportCaseError[] = [];
Why this variable ?

2024-03-08 16:11 UTC, SlimaneAmar commented on src/components/utils/caseUtils.ts
> +    const handleCaseExportError = (caseUuid: string, errorMsg: string) =>
uuid for user is not human readable !
Pass `selectedElements` in order to get names

2024-03-08 16:25 UTC, SlimaneAmar approved these changes

2024-03-13 15:32 UTC, merged