Expert filter enhancement
gridsuite/gridexplore-app pull request #396
Opened 2024-03-28 13:17 UTC by AAJELLAL

2024-04-03 14:40 UTC, ayolab requested changes

2024-04-03 14:40 UTC, ayolab commented on src/translations/en.json
>    "ratioTargetV": "Ratio voltage set point",
```suggestion
  "ratioTargetV": "Ratio voltage set point (kV)",
```

2024-04-03 14:40 UTC, ayolab commented on src/translations/en.json
>    "SwitchedOnMaxSusceptance": "Switch-on susceptance",
```suggestion
  "SwitchedOnMaxSusceptance": "Switch-on susceptance (S)",
```

2024-04-03 14:40 UTC, ayolab commented on src/translations/en.json
>    "maxSusceptance": "Maximum available susceptance",
```suggestion
  "maxSusceptance": "Maximum available susceptance (S)",
```

2024-04-03 14:40 UTC, ayolab commented on src/translations/en.json
>    "SwitchedOnMaxQAtNominalV": "Switch-on Q at nominal voltage",
"maxQAtNominalV": "Available Qmax at nominal voltage (MVar)",
```suggestion
  "SwitchedOnMaxQAtNominalV": "Switch-on Q at nominal voltage (MVar)",
```

2024-04-03 14:40 UTC, ayolab commented on src/translations/en.json
> +  "ratedS": "Rated nominal power (MW)",
```suggestion
  "ratedS": "Rated nominal power (MVA)",
```

2024-04-04 15:30 UTC, anistouri approved these changes

2024-04-05 09:41 UTC, AAJELLAL commented on src/translations/en.json
> +  "ratedS": "Rated nominal power (MW)",
Done

2024-04-05 09:41 UTC, AAJELLAL commented on src/translations/en.json
>    "SwitchedOnMaxQAtNominalV": "Switch-on Q at nominal voltage",
Done

2024-04-05 09:41 UTC, AAJELLAL commented on src/translations/en.json
>    "maxSusceptance": "Maximum available susceptance",
Done

2024-04-05 09:41 UTC, AAJELLAL commented on src/translations/en.json
>    "SwitchedOnMaxSusceptance": "Switch-on susceptance",
Done

2024-04-05 09:42 UTC, AAJELLAL commented on src/translations/en.json
>    "ratioTargetV": "Ratio voltage set point",
Done

2024-04-05 10:02 UTC, ayolab approved these changes

2024-04-05 11:01 UTC, merged