Update server port to 3001
gridsuite/gridexplore-app pull request #397
Opened 2024-03-28 14:18 UTC by flomillot

2024-03-28 15:06 UTC, Tristan-WorkGH requested changes

2024-03-28 15:06 UTC, Tristan-WorkGH commented on package.json
> +        "start": "PORT=3001 react-scripts start",
```suggestion
        "start": "PORT=3000 react-scripts start",
```

2024-03-28 15:06 UTC, Tristan-WorkGH commented on public/idpSettings.json
> +    "silent_redirect_uri": "http://localhost:3001/silent-renew-callback",
```suggestion
    "redirect_uri": "http://localhost:3000/sign-in-callback",
    "post_logout_redirect_uri": "http://localhost:3000/logout-callback",
    "silent_redirect_uri": "http://localhost:3000/silent-renew-callback",
```

2024-03-28 17:24 UTC, Tristan-WorkGH approved these changes

2024-03-29 08:28 UTC, EstherDarkish approved these changes

2024-04-02 10:50 UTC, merged