Revert stash from codebase
gridsuite/gridexplore-app pull request #408
Opened 2024-04-12 15:09 UTC by klesaulnier

2024-04-18 10:03 UTC, TheMaskedTurtle requested changes

2024-04-18 10:03 UTC, TheMaskedTurtle commented on src/utils/rest-api.js
>  export function restoreElements(elementUuids, activeDirectory) {
This one should be deleted too

2024-04-18 12:44 UTC, YenguiSeddik approved these changes
Code: As mentioned, the function restoreElements should be deleted also. otherwise ok
test: ok

2024-04-19 08:03 UTC, TheMaskedTurtle approved these changes

2024-04-22 10:34 UTC, merged