Feed language to form context instead of Custom mui dialog
gridsuite/gridexplore-app pull request #421
Opened 2024-04-30 13:08 UTC by Meklo

2024-05-07 11:01 UTC, flomillot requested changes

2024-05-07 11:01 UTC, flomillot commented on src/components/dialogs/contingency-list/creation/contingency-list-creation-dialog.jsx
> +        language: languageLocal,
Language is not a form method and shouldn't be mixed with.
You need to change a bit commons-ui instead, and not this part.

```
        <CustomFormProvider
            {...formMethods}
            validationSchema={formSchema}
            removeOptional={removeOptional}
            **language={language}**
        >
```

2024-05-13 12:34 UTC, Meklo commented on src/components/dialogs/contingency-list/creation/contingency-list-creation-dialog.jsx
> +        language: languageLocal,
Alright it is done, here is the corresponding PR [#440](https://github.com/gridsuite/commons-ui/pull/440)

2024-05-14 08:43 UTC, flomillot approved these changes

2024-05-14 08:52 UTC, Meklo commented
Waiting for next commons ui release before merge

2024-05-17 15:25 UTC, merged