Remove mutualized functions
gridsuite/gridexplore-app pull request #434
Opened 2024-05-23 12:21 UTC by Meklo

2024-05-24 14:21 UTC, flomillot requested changes
You didn't deleted most of the functions imported in commons-ui.
fetchEnv, fetchAppsAndUrl, fetchBackEnd, etc...

2024-05-27 15:29 UTC, flomillot approved these changes

2024-05-27 19:01 UTC, Tristan-WorkGH commented on src/utils/rest-api.js
> +  backendFetchText, getRequestParamFromList
prettier let this pass?
```suggestion
  backendFetchText,
  getRequestParamFromList,
```

2024-05-27 19:04 UTC, Tristan-WorkGH requested changes
`commons-ui` version not updated in `package.json`

2024-05-28 08:05 UTC, flomillot commented
I forgot : need to use getToken from commons-ui too (if TL approve)

2024-05-28 13:56 UTC, Meklo commented
> I forgot : need to use getToken from commons-ui too (if TL approve)

Done

2024-06-07 13:43 UTC, Tristan-WorkGH approved these changes

2024-06-07 14:26 UTC, merged