Add csv config to contingency list creation
gridsuite/gridexplore-app pull request #441
Opened 2024-06-07 06:56 UTC by YenguiSeddik

2024-06-10 14:23 UTC, jamal-khey approved these changes
Code Ok
Console logs Ok
Test Ok

2024-06-17 08:16 UTC, sBouzols commented on src/components/dialogs/contingency-list/explicit-naming/explicit-naming-form.jsx
> +                config: { delimiter: ',' },
Why fixing the delimiter to ',' ?
We should used `delimitersToGuess` prop and juste remove the one we use for multiple values here '|'
see https://react-papaparse.js.org/docs#config : 
```diff
-delimitersToGuess: [',', '	', '|', ';', RECORD_SEP, UNIT_SEP]
+delimitersToGuess: [',', '	', ';', RECORD_SEP, UNIT_SEP]
```

2024-06-17 08:18 UTC, sBouzols commented on src/components/dialogs/contingency-list/explicit-naming/explicit-naming-form.jsx
> +                config: { delimiter: ',' },
And we could fix this rule directly in commons-ui to avoid knowing papaparse here.

2024-06-18 12:37 UTC, sBouzols requested changes
do not merge this PR.
Must be fixed for all CSV parse workflow then fix it in commons-ui

2024-06-18 15:02 UTC, jamal-khey commented
delimiter config has been moved to commun-ui and merged.
this pr is not usefull any more

2024-06-18 15:02 UTC, closed without merging