Add a confirmation popup for study/case creation based on env property
gridsuite/gridexplore-app pull request #487
Opened 2024-08-06 12:36 UTC by dbraquart

The goal is to define this property/behaviour for demo env only

2024-08-07 16:24 UTC, ayolab approved these changes

2024-08-09 10:25 UTC, Tristan-WorkGH requested changes

2024-08-09 10:25 UTC, Tristan-WorkGH commented on src/hooks/useConfidentialityWarning.ts
maybe to move to commons-ui?

2024-08-09 10:25 UTC, Tristan-WorkGH commented on src/hooks/useConfidentialityWarning.ts
> +export const useConfidentialityWarning = () => {
```suggestion
export const useConfidentialityWarningKey = () => {
```

2024-08-09 10:25 UTC, Tristan-WorkGH commented on src/components/dialogs/create-study-dialog/create-study-dialog.jsx
> +    const confidentialityWarning = useConfidentialityWarning();
```suggestion
    const confidentialityWarningKey = useConfidentialityWarning();
```

2024-08-09 10:25 UTC, Tristan-WorkGH commented on src/components/dialogs/create-case-dialog/create-case-dialog.tsx
> +    const confidentialityWarning = useConfidentialityWarning();
```suggestion
    const confidentialityWarningKey = useConfidentialityWarningKey();
```

2024-08-09 10:25 UTC, Tristan-WorkGH commented on src/components/dialogs/create-case-dialog/create-case-dialog.tsx
> +            confirmationMessage={confidentialityWarning}
```suggestion
            confirmationMessageKey={confidentialityWarningKey}
```

2024-08-09 10:25 UTC, Tristan-WorkGH commented on src/hooks/useConfidentialityWarning.ts
> +    const [confidentialityWarning, setConfidentialityWarning] = useState<string>();
```suggestion
    const [confidentialityWarning, setConfidentialityWarning] = useState<string>('');
```

2024-08-12 14:30 UTC, dbraquart commented on src/hooks/useConfidentialityWarning.ts
> +export const useConfidentialityWarning = () => {
For the hook itself, it sounds better without 'Key'

2024-08-14 07:51 UTC, Tristan-WorkGH approved these changes

2024-08-19 09:06 UTC, merged