Add spreadsheet config element
gridsuite/gridexplore-app pull request #527
Opened 2024-09-26 15:11 UTC by achour94

2024-09-30 09:25 UTC, FranckLecuyer requested changes
Tests: 
Missing equipement type in parenthesis after 'Spreadsheet model' in column 'Type'
Maybe prettify the json result when downloading a spreadsheet_config ?

2024-09-30 09:25 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "download.message.downloadedElement": "Un élément a été téléchargée.",
Typo : téléchargé

2024-09-30 09:25 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "download.message.downloadedElements": "{number} éléments ont été téléchargées.",
Typo: téléchargés

2024-09-30 09:25 UTC, FranckLecuyer commented on src/components/menus/directory-tree-contextual-menu.tsx
> +                case ElementType.SPREADSHEET_CONFIG:
You should also add the SPREADSHEET_CONFIG element type in the not clickable elements in getClickableRowStyle function in directory-content-table.tsx

2024-10-01 07:22 UTC, FranckLecuyer approved these changes

2024-10-01 07:25 UTC, AbdelHedhili approved these changes

2024-10-01 07:25 UTC, AbdelHedhili commented on src/components/menus/content-contextual-menu.tsx
> +    const allowsDuplicateAndCopy = useCallback(() => {
why this rename, isn't copying and duplicating the same thing

2024-10-01 14:46 UTC, merged