Migrate to ESLint AirBnB rules
gridsuite/gridexplore-app pull request #546
Opened 2024-10-21 10:35 UTC by Tristan-WorkGH

2024-10-23 12:08 UTC, Meklo requested changes
There's a new warning when opening directory contextual menu : 
`Warning: Encountered two children with the same key, .$divider-no_msg. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

2024-10-23 12:08 UTC, Meklo commented on src/components/dialogs/commons/upload-new-case.tsx
>                      ) : caseFileName ? (
How about externalizing the nested ternary in a render function with if else statements ?

2024-10-23 12:08 UTC, Meklo commented on src/components/dialogs/contingency-list/contingency-list-utils.ts
> +
?

2024-10-23 12:08 UTC, Meklo commented on src/module-emotion.d.ts
> +/* eslint-disable spaced-comment */
How about removing the comment ?

2024-10-23 12:08 UTC, Meklo commented on src/components/dialogs/create-case-dialog/create-case-dialog.tsx
>                  } else if (err?.status === HTTP_UNPROCESSABLE_ENTITY_STATUS) {
How about incorporating `!handleMaxElementsExceededError` to the second if else statement ?

2024-10-23 12:08 UTC, Meklo commented on src/components/dialogs/create-study-dialog/create-study-dialog-utils.ts
> +    // @ts-expect-error how react-hook manage strings like UUIDs?
One way could be using `randomUUID()` from `crypto`

2024-10-23 12:08 UTC, Meklo commented on src/components/directory-breadcrumbs.tsx
> +    const currentPath = useSelector((state: AppState) => state.currentPath as any[]);
Shouldn't it be typed as `ElementAttributes[]` ?

2024-10-23 12:08 UTC, Meklo commented on src/components/directory-tree-view.tsx
> +    const currentPath = useSelector((state: AppState) => state.currentPath as any[]);
Shouldn't it be typed as `ElementAttributes[]` ?

2024-10-23 12:08 UTC, Meklo commented on src/utils/custom-hooks.ts
> +): [(...args: TArgs) => void, FetchState<T>] => {
Is this change really worth ? It seems it brings a lot of ts-expect-error annotations

2024-10-23 12:08 UTC, Meklo commented on src/utils/custom-hooks.ts
> +/// //////////////////////////////////////////////////////////////:
?

2024-10-23 12:08 UTC, Meklo commented on src/components/search/search-bar.tsx
>  type ElementSearchInputProps<T> = Parameters<typeof ElementSearchInput<T>>[0];
I reckon it's now available from commons ui

2024-10-23 12:08 UTC, Meklo commented on src/components/utils/directory-content-utils.ts
> -    suppressHorizontalScroll: true,
Why this removal ?

2024-10-23 12:33 UTC, dbraquart reviewed
code: ok - just a few questions
tests: still on-going

2024-10-23 12:33 UTC, dbraquart commented on src/components/menus/common-contextual-menu.tsx
> +                            key={`${menuItem.isDivider ? 'divider' : 'menu'}-${
why changing the key value ?

2024-10-23 12:33 UTC, dbraquart commented on src/components/custom-tree-item.tsx
>  }
where you forced by the linter to make so many changes in this file ?

2024-10-23 12:33 UTC, dbraquart commented on src/components/dialogs/export-case-dialog.tsx
> +                Array.isArray(fetchedFormats)
I dont understand the use of isArray here

2024-10-23 12:33 UTC, dbraquart commented on src/components/search/search-item.tsx
> +                        key={`part-${part.toLowerCase().replace(/[^[a-z]\d.-]+/g, '-')}`}
why changing the key here ?

2024-10-23 12:33 UTC, dbraquart commented on src/translations/dynamic/network-modifications-locale-en.ts
> +const NetworkModificationsLocaleEn = {
This file is useless. Will create a US for that.

2024-10-23 12:33 UTC, dbraquart commented on src/translations/dynamic/network-modifications-locale-fr.ts
> +const NetworkModificationsLocaleFr = {
This file is useless. Will create a US for that.

2024-10-23 14:12 UTC, FranckLecuyer reviewed
Tests: OK

2024-10-25 07:48 UTC, Tristan-WorkGH commented on src/components/dialogs/commons/upload-new-case.tsx
>                      ) : caseFileName ? (
Found a way around with a `useMemo`.

2024-10-25 07:48 UTC, Tristan-WorkGH commented on src/module-emotion.d.ts
> +/* eslint-disable spaced-comment */
It's present on commons-ui as reference for these particular files.

2024-10-25 07:49 UTC, Tristan-WorkGH commented on src/components/directory-tree-view.tsx
> +    const currentPath = useSelector((state: AppState) => state.currentPath as any[]);
Dunno, in the redux definition it's done as `unknown[]` which pose problems of types after.

2024-10-25 07:49 UTC, Tristan-WorkGH commented on src/components/directory-breadcrumbs.tsx
> +    const currentPath = useSelector((state: AppState) => state.currentPath as any[]);
https://github.com/gridsuite/gridexplore-app/pull/546#discussion_r1816172547

2024-10-25 07:49 UTC, Tristan-WorkGH commented on src/utils/custom-hooks.ts
> +): [(...args: TArgs) => void, FetchState<T>] => {
Yes, because now typescript can infer what the function return.

2024-10-25 07:50 UTC, Tristan-WorkGH commented on src/utils/custom-hooks.ts
> +/// //////////////////////////////////////////////////////////////:
New rule:
> ESLint: Expected exception block, space or tab after '//' in comment.(spaced-comment)

2024-10-25 07:51 UTC, Tristan-WorkGH commented on src/components/utils/directory-content-utils.ts
> -    suppressHorizontalScroll: true,
TypeScript error: this parameter does not exist in AgGrid, adding `ColDef` type help typescript to confirm that.

2024-10-25 07:51 UTC, Tristan-WorkGH commented on src/components/dialogs/create-study-dialog/create-study-dialog-utils.ts
> +    // @ts-expect-error how react-hook manage strings like UUIDs?
@klesaulnier has explain to me that the problem we have is that react and typescript consider `undefined` for not defined values, and react-hook-form consider `null` for them...

2024-10-25 07:51 UTC, Tristan-WorkGH commented on src/components/menus/common-contextual-menu.tsx
> +                            key={`${menuItem.isDivider ? 'divider' : 'menu'}-${
I had error of not using index in the key attribute.

2024-10-25 07:51 UTC, Tristan-WorkGH commented on src/components/custom-tree-item.tsx
>  }
Yes but not sure, there is a confusion with the classes system of the Tree components and the styles of Mui.

2024-10-25 07:52 UTC, Tristan-WorkGH commented on src/components/dialogs/export-case-dialog.tsx
> +                Array.isArray(fetchedFormats)
Types error: `fetchedFormats` is of `ExportFormats` type which is define as `type ExportFormats = { [p: string]: {/*...*/} } | []` so I need to known if it's a object before exploring it.

2024-10-25 07:52 UTC, Tristan-WorkGH commented on src/components/search/search-item.tsx
> +                        key={`part-${part.toLowerCase().replace(/[^[a-z]\d.-]+/g, '-')}`}
https://github.com/gridsuite/gridexplore-app/pull/546#discussion_r1816175769

2024-10-28 13:21 UTC, dbraquart reviewed
code ok
tests ok

just waiting for conflicts resolution

2024-10-29 15:06 UTC, Meklo approved these changes

2024-10-29 15:16 UTC, dbraquart approved these changes

2024-10-29 15:17 UTC, merged