Refactor use of `SelectionForCopy` and `isStudyMetadata`
gridsuite/gridexplore-app pull request #571
Opened 2024-11-26 08:47 UTC by Tristan-WorkGH

Need gridsuite/commons-ui#644

2024-12-02 14:47 UTC, anistouri requested changes
Rename the elements you renamed in commons-ui   : 
SelectionForCopy with ItemSelectionForCopy 
NO_SELECTION_FOR_COPY with NO_ITEM_SELECTION_FOR_COPY

2024-12-11 08:28 UTC, Tristan-WorkGH commented
> Rename the elements you renamed in commons-ui : SelectionForCopy with ItemSelectionForCopy NO_SELECTION_FOR_COPY with NO_ITEM_SELECTION_FOR_COPY

Where ?

2024-12-11 08:57 UTC, anistouri commented
> > Rename the elements you renamed in commons-ui : SelectionForCopy with ItemSelectionForCopy NO_SELECTION_FOR_COPY with NO_ITEM_SELECTION_FOR_COPY
> 
> Where ?

src/components/directory-content.tsx
src/components/dialogs/contingency-list/edition/criteria-based/criteria-based-edition-dialog.tsx
src/components/dialogs/contingency-list/edition/explicit-naming/explicit-naming-edition-dialog.tsx
src/components/dialogs/contingency-list/edition/script/script-edition-dialog.tsx
src/components/dialogs/network-modification/composite-modification/composite-modification-dialog.tsx

2024-12-13 16:22 UTC, anistouri approved these changes

2024-12-16 08:42 UTC, merged