Case import : compute base name from case-server instead of front com…
gridsuite/gridexplore-app pull request #587
Opened 2024-12-26 09:39 UTC by basseche

…putation

2025-01-03 08:11 UTC, ghazwarhili requested changes

2025-01-03 08:11 UTC, ghazwarhili commented on src/components/dialogs/create-case-dialog/create-case-dialog.tsx
> +            <UploadNewCase isNewStudyCreation />
Why did you add isNewStudyCreation to the create-case-dialog? The UploadNewCase component is shared between case and study, and this variable is used to distinguish between the two.

2025-01-03 08:11 UTC, ghazwarhili commented on src/components/dialogs/commons/prefilled-name-input.tsx
> +            if (caseName && caseName !== currentCaseName) {
caseName = basename + extension (PtFige-20241120-1520-enrichi_N1.zip )
currentCaseName = basename (PtFige-20241120-1520-enrichi_N1)

caseName !== currentCaseName is always true.

2025-01-03 09:03 UTC, basseche commented on src/components/dialogs/commons/prefilled-name-input.tsx
> +            if (caseName && caseName !== currentCaseName) {
yes you are right. I wanted only to check if file doesn't change in file name.

2025-01-03 10:37 UTC, basseche commented on src/components/dialogs/create-case-dialog/create-case-dialog.tsx
> +            <UploadNewCase isNewStudyCreation />
ok

2025-01-06 08:02 UTC, basseche commented
> [ suggestion to fix this PR](https://github.com/gridsuite/gridexplore-app/pull/592#issue-2759542134)

The problem with this fix that : 
- it will introduce a bug, because it doesn't take into account user modification of the name, it will always calls endPoint.
- it does not solve problem of UniqueNameInput component.
- it is a refactoring it will make PrefilledNameInput component obsolete and we should remove it.

2025-01-06 13:35 UTC, ghazwarhili commented
I didn't say this is the final solution.. it's a proposal or suggestion to properly implement the new endpoint, like a first version to be completed.

2025-01-09 13:54 UTC, thangqp approved these changes

2025-01-14 09:46 UTC, ghazwarhili approved these changes

2025-01-14 14:49 UTC, merged